# /wordpress-docker/docker-compose.yml
---
version: '3.8'
services:
  web:
    container_name: nginx
    depends_on:
      - db2
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/app
    links:
      - php
      - db2
  php:
    container_name: php
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./app:/app
    links:
      - db2
  db2:
    container_name: db2
    image: ibmcom/db2:latest
    hostname: db2.rn.dk
    privileged: true
    ports:
      - "50000:50000"
    environment:
      - DBNAME=testdb
      - DB2INSTANCE=db2inst1
      - DB2INST1_PASSWORD=ChangeMe!
      - LICENSE=accept
      # - SAMPLEDB=true
      ## Creates the database DB_NAME, if its not exists
      # - STARTUP_MODE=createIfNotExists
      # - DB_CREATE_SCRIPT=create_wdemo.sql
      ## loads an old backup of DB_NAME, 
      ## if the dabase DB_NAME does not exist
      # - STARTUP_MODE=restoreIfNotExists
      # - DB_BACKUP=wdemo.tar.gz
    volumes:
      - './data/db2:/database'